FROM node:22-slim

WORKDIR /app

# ติดตั้ง dependencies
COPY package.json package-lock.json ./
RUN npm install

# mount โค้ดเข้ามาทีหลังผ่าน docker-compose
COPY . .

EXPOSE 5123

CMD ["npm", "run", "docs:dev", "--", "--host", "0.0.0.0"]
